input_number = input("Введите пятизначное число: ")
input_number_list = list(input_number)
print(input_number_list)
middle = list(input_number_list[1:-1])
print(middle)
reversed_middle = list(reversed(middle))
print(reversed_middle)
reversed_middle_str = ''.join(reversed_middle)
print(reversed_middle_str)
list_ = (input_number_list[0],reversed_middle_str,input_number_list[-1])
print(list_)
list__ = ''.join(list_)
print(list__)